networks:
  toubilib.net:
    driver: bridge

services:
  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubilib:
    build:
      context: docker/php8.4-cli
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


  api.praticiens:
    build:
      context: docker/php8.4-cli
    ports:
      - '6081:80'
    volumes:
      - ./app-praticiens:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


  api.rdvs:
    build:
      context: docker/php8.4-cli
    ports:
      - '6082:80'
    volumes:
      - ./app-rdv:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - toubiprati.db
      - toubiauth.db
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"


    # service toubiprat.db : base de donn√©es postgresql pour les praticiens
  toubiprati.db:
    image: 'postgres:latest'
    env_file: ./toubipratdb.env
    networks:
      - toubilib.net
    volumes:
      - ./sql/toubiprat:/docker-entrypoint-initdb.d



  toubirdv.db:
    image: 'postgres:latest'
    env_file: ./toubirdvdb.env
    networks:
      - toubilib.net
    volumes:
      - ./sql/toubirdv:/docker-entrypoint-initdb.d

  toubipatient.db:
    image: 'postgres:latest'
    env_file: ./toubipatient.env
    networks:
      - toubilib.net
    volumes:
      - ./sql/toubipat:/docker-entrypoint-initdb.d

  toubiauth.db:
    image: 'postgres:latest'
    env_file: ./toubiauthdb.env
    networks:
      - toubilib.net
    volumes:
      - ./sql/toubiauth:/docker-entrypoint-initdb.d


  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8181:8080'
    networks:
      - toubilib.net

  gateway:
    build:
      context: docker/php8.4-cli
    ports:
      - '7080:80'
    volumes:
      - ./gateway:/var/php
    working_dir: /var/php
    networks:
      - toubilib.net
    depends_on:
      - api.toubilib
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public"